name: EduParkour
description: Minigame Parkour basendo em Parkours da vida
main: net.eduard.parkour.Main
version: 1.0-SNAPSHOT
author: Eduard
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  parkour:
    aliases: [pk,pa]
    usage: /<command>
    description: Comando Principal do Parkour